import type { AgentAuthorship, AgentTool } from "../types";
import { fetchWithTimeout, githubHeaders, parseRepoSlug } from "./version-utils";
import { cacheGet, cacheSet } from "../cache";
import { logger } from "../logger";

/**
 * Agent-Authored Commit Ratio scanner.
 *
 * ACR = (commits with AI co-author markers) / (total commits)
 * over a 90-day window. Operationalizes the §5.4.3 metric for per-project
 * monitoring. ACR is a *conservative lower bound* — many AI-assisted commits
 * lack markers (Copilot/Cursor rarely annotate).
 */

const WINDOW_DAYS = 90;
const ACR_TTL_MS = 60 * 60 * 1000; // 1h
const MAX_COMMITS_INSPECTED = 500; // sample cap; sets `sampled: true` if reached

/* ── AI agent detection ── */

const AI_COAUTHOR_PATTERNS: RegExp[] = [
  /co-authored-by:.*\bclaude\b/i,
  /co-authored-by:.*\banthropic\b/i,
  /co-authored-by:.*\bcopilot\b/i,
  /co-authored-by:.*\bcursor\b/i,
  /co-authored-by:.*\bdevin\b/i,
  /co-authored-by:.*\bcognition\b/i,
  /co-authored-by:.*\baider\b/i,
  /co-authored-by:.*\bcody\b/i,
  /co-authored-by:.*\bsourcegraph\b/i,
  /co-authored-by:.*\bsweep\b/i,
  /co-authored-by:.*\btabnine\b/i,
  /co-authored-by:.*\bamazon-q\b/i,
  /co-authored-by:.*\bwindsurf\b/i,
  /co-authored-by:.*\bcodeium\b/i,
];

const AI_AUTHOR_LOGIN_PATTERNS: RegExp[] = [
  /devin-ai\[bot\]/i,
  /sweep-ai\[bot\]/i,
  /coderabbit.*\[bot\]/i,
  /ellipsis-dev\[bot\]/i,
  /sourcery-ai\[bot\]/i,
  /codeflash-ai\[bot\]/i,
];

const AI_MESSAGE_PATTERNS: RegExp[] = [
  /\bgenerated by (?:claude|copilot|cursor|devin|cody|aider)\b/i,
];

/* ── Traditional bot detection ── */

const BOT_AUTHOR_PATTERNS: RegExp[] = [
  /dependabot\[bot\]/i,
  /renovate\[bot\]/i,
  /github-actions\[bot\]/i,
  /greenkeeper\[bot\]/i,
  /snyk-bot/i,
  /codecov\[bot\]/i,
  /netlify\[bot\]/i,
  /vercel\[bot\]/i,
  /semantic-release-bot/i,
];

const BOT_LOGIN_TRAILER = /\[bot\]$/i;

type CommitClass = "ai-agent" | "bot" | "human";

interface CommitClassification {
  klass: CommitClass;
  tool?: AgentTool;
}

export function detectAgentTool(text: string): AgentTool {
  const lower = text.toLowerCase();
  if (/claude|anthropic/.test(lower)) return "claude";
  if (/copilot/.test(lower)) return "copilot";
  if (/cursor/.test(lower)) return "cursor";
  if (/devin|cognition/.test(lower)) return "devin";
  return "other";
}

export function classifyCommit(commit: unknown): CommitClassification {
  const c = commit as {
    commit?: { message?: string; author?: { email?: string }; committer?: { email?: string } };
    author?: { login?: string };
    committer?: { login?: string };
  };
  const message = c.commit?.message ?? "";
  const authorLogin = c.author?.login ?? "";
  const committerLogin = c.committer?.login ?? "";
  const authorEmail = c.commit?.author?.email ?? "";
  const committerEmail = c.commit?.committer?.email ?? "";

  // 1. AI co-author markers in commit message
  for (const p of AI_COAUTHOR_PATTERNS) {
    if (p.test(message)) {
      return { klass: "ai-agent", tool: detectAgentTool(message) };
    }
  }
  // 2. Known AI bot account logins
  for (const p of AI_AUTHOR_LOGIN_PATTERNS) {
    if (p.test(authorLogin) || p.test(committerLogin)) {
      return {
        klass: "ai-agent",
        tool: detectAgentTool(`${authorLogin} ${committerLogin}`),
      };
    }
  }
  // 3. AI message hints ("generated by claude")
  for (const p of AI_MESSAGE_PATTERNS) {
    if (p.test(message)) {
      return { klass: "ai-agent", tool: detectAgentTool(message) };
    }
  }
  // 4. Traditional automation bots
  for (const p of BOT_AUTHOR_PATTERNS) {
    if (
      p.test(authorLogin) || p.test(committerLogin) ||
      p.test(authorEmail) || p.test(committerEmail)
    ) {
      return { klass: "bot" };
    }
  }
  // 5. Generic [bot] suffix
  if (BOT_LOGIN_TRAILER.test(authorLogin) || BOT_LOGIN_TRAILER.test(committerLogin)) {
    return { klass: "bot" };
  }

  return { klass: "human" };
}

function emptyToolBreakdown(): Record<AgentTool, number> {
  return { claude: 0, copilot: 0, cursor: 0, devin: 0, other: 0 };
}

function pickDominantTool(breakdown: Record<AgentTool, number>): AgentTool | null {
  let best: AgentTool | null = null;
  let bestCount = 0;
  for (const [tool, count] of Object.entries(breakdown) as [AgentTool, number][]) {
    if (count > bestCount) {
      best = tool;
      bestCount = count;
    }
  }
  return best;
}

async function fetchCommitsPaged(
  owner: string,
  name: string,
  sinceISO: string,
): Promise<{ commits: unknown[]; sampled: boolean }> {
  const collected: unknown[] = [];
  let page = 1;
  const perPage = 100;
  let sampled = false;
  while (collected.length < MAX_COMMITS_INSPECTED) {
    const url =
      `https://api.github.com/repos/${owner}/${name}/commits` +
      `?since=${encodeURIComponent(sinceISO)}&per_page=${perPage}&page=${page}`;
    const res = await fetchWithTimeout(url, { headers: githubHeaders() }, 12000);
    if (!res.ok) break;
    const batch = await res.json();
    if (!Array.isArray(batch) || batch.length === 0) break;
    for (const c of batch) {
      if (collected.length >= MAX_COMMITS_INSPECTED) {
        sampled = true;
        break;
      }
      collected.push(c);
    }
    if (batch.length < perPage) break;
    page++;
  }
  return { commits: collected, sampled };
}

export async function checkAgentAuthorship(
  repo: string,
): Promise<AgentAuthorship | null> {
  const parsed = parseRepoSlug(repo);
  if (!parsed) return null;
  const { owner, name } = parsed;

  const cacheKey = `acr:${owner}/${name}:${WINDOW_DAYS}d`;
  const cached = cacheGet<AgentAuthorship>(cacheKey);
  if (cached) return cached;

  try {
    const sinceISO = new Date(
      Date.now() - WINDOW_DAYS * 24 * 60 * 60 * 1000,
    ).toISOString();

    const { commits, sampled } = await fetchCommitsPaged(owner, name, sinceISO);
    if (commits.length === 0) {
      const empty: AgentAuthorship = {
        acr: 0,
        totalCommits: 0,
        agentCommits: 0,
        botCommits: 0,
        toolBreakdown: emptyToolBreakdown(),
        dominantTool: null,
        sampled,
        windowDays: WINDOW_DAYS,
        lastChecked: new Date().toISOString(),
      };
      cacheSet(cacheKey, empty, ACR_TTL_MS);
      return empty;
    }

    const toolBreakdown = emptyToolBreakdown();
    let agentCommits = 0;
    let botCommits = 0;

    for (const c of commits) {
      const { klass, tool } = classifyCommit(c);
      if (klass === "ai-agent") {
        agentCommits++;
        if (tool) toolBreakdown[tool]++;
      } else if (klass === "bot") {
        botCommits++;
      }
    }

    const result: AgentAuthorship = {
      acr: commits.length > 0 ? agentCommits / commits.length : 0,
      totalCommits: commits.length,
      agentCommits,
      botCommits,
      toolBreakdown,
      dominantTool: pickDominantTool(toolBreakdown),
      sampled,
      windowDays: WINDOW_DAYS,
      lastChecked: new Date().toISOString(),
    };

    cacheSet(cacheKey, result, ACR_TTL_MS);
    return result;
  } catch (err) {
    logger.error("acr: scan failed", {
      repo,
      error: err instanceof Error ? err.message : String(err),
    });
    return null;
  }
}
